export const BASE_URL = 'http://localhost:5000/';
export const NANOSECONDS_PY = 1;
export const MICROSECONDS_PY = 1000 * NANOSECONDS_PY;
export const MILLISECONDS_PY = 1000 * MICROSECONDS_PY;

const MILLISECONDS_JS = 1;
const SECONDS_JS = MILLISECONDS_JS * 1000

export { MILLISECONDS_JS, SECONDS_JS }